#!/bin/bash

# check if the script was executed directly
if [[ "${BASH_SOURCE[0]}" == "${0}" ]]; then
    echo "The script was executed directly, it needs to be launched with source/."
    echo "Usage: source build.sh"
    echo "Usage: . build.sh"
    exit -1
fi

# sanity check
if [ ! -d "./linux_venv" ]; then
    echo "Error: virtual environment not found. Run 'build_venv\ first."
    return -1
fi

source ./linux_venv/bin/activate

# add python version message
python --version
echo "Python enviroment launched, to exit the virtual environment, run 'deactivate'."
